# frozen_string_literal: true

require_relative "open_project/add_preview_for_view_component"
require_relative "open_project/no_do_end_block_with_rspec_capybara_matcher_in_expect"
require_relative "open_project/use_service_result_factory_methods"
